name: Python Linting

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint black
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run Black formatter check
      run: |
        black --check --diff .
        
    - name: Run PyLint
      run: |
        pylint --disable=C0111,C0103 $(git ls-files '*.py')